### ISSUE TITLE
Publish 3D models for v1 enclosure in STEP or IGES format

### ISSUE THREAD

**Issue by 57Bravo** [sqfmi/beepberry-hardware#5]
The v1 enclosure looks great. Can the models be published as STEP or IGES files as well? Although STL's can be manipulated in FreeCAD using mesh to object conversion, the result is typically harder to work with than a direct export to STEP/IGES.

**Comment by sqfmi** [comment]
added :)

**Comment by 57Bravo** [comment]
Looks good, thanks.
